### PR TITLE
Account setup alert ordering

### LINKED ISSUE #912: streamline avatar selection menu in profile after qr-account-scan
- order should be "camera" atop and "gallery" below (as in chat)
- ~~group avatar selection lacks the option "delete"~~

in the group-profile and normal-profile, this was streamlined in #879, however, if was overseen for the the after-qr-scan-profile

### PR DESCRIPTION
**Pull request by nayooti**
closes #912 

## For testing:
From WelcomeScreen -> Scan QR-Code -> You will be redirected to ProfileSetup-Screen -> Tap Empty Avatar 
- Ordering changed 
 Then: Select Avatar  -> Tap Avatar:
- Option to delete avatar in alert
Then: delete avatar -> Avatar is empty

### CODE REVIEW

**Comment by r10s** [comment]
for whatever reasons, this pr is based on https://github.com/deltachat/deltachat-ios/pull/1000 - i think, this needs a rebase on master.

**Comment by nayooti** [comment]
I accidently created branch not from master.

**Comment by nayooti** [comment]
Can someone please review this mini PR? @r10s  @cyBerta

**Review by cyBerta — APPROVED** [review]
code lgtm, didn't test it though

**Comment by cyBerta** [comment]
I tested now the PR. What is missing yet, is the option to crop an image. This option is enabled in group profile, group creation etc. This issue can be handled in a seperate PR though.

**Pull request merged**
