### PR TITLE
add basic context menu

### PR DESCRIPTION
**Pull request by r10s**

### CODE REVIEW

**Comment by r10s** [comment]
@cyBerta this pr has the problem that the context menu does not disappear when tapped outside.

after some research, i figured out that the `self.tableView.becomeFirstResponder()` stops the context menu from working, not totally sure, what the reason for this is, maybe the input does not "give up" the responder state or so.

**Comment by cyBerta** [comment]
shall I have a look at it?

**Comment by r10s** [comment]
@cyBerta that would be great, i am a bit out of ideas. but we can also have an a/v on that these days (as you have time :) (but tonight i am offline :)

**Comment by r10s** [comment]
great, much better now. so one has to hide the menu manually ... tbh, i did not expect that :)

**Pull request merged**
