### PR TITLE
[wip] switch accounts

### PR DESCRIPTION
**Pull request by r10s**
once done, this pr will add multi-account support to deltachat-ios as described in #829

### CODE REVIEW

**Comment by r10s** [comment]
mb: this will probably a bit postponed and incorporated with upcoming core-multi-account-support from https://github.com/deltachat/deltachat-core-rust/pull/1784

**Comment by r10s** [comment]
closing this for now, we will reopen when we continue work on that.

**Comment by cedk** [comment]
https://github.com/deltachat/deltachat-core-rust/pull/1784 has been merged.
It will be great if switch accounts were implemented for iOS.

**Comment by r10s** [comment]
> It will be great if switch accounts were implemented for iOS.

i totally agree! :)

**Pull request closed without merging**
