### PR TITLE
force initiating preview with correct size

### LINKED ISSUE #1285: fix share layout for ipads
tested on an ipad simulator:

simulator_screenshot_5CF797B1-18DE-420E-8EFE-EB1D2F601B20

### PR DESCRIPTION
**Pull request by cyBerta**
fixes #1285

### CODE REVIEW

**Comment by r10s** [comment]
ah, so that scales up the preview window?

**Comment by cyBerta** [comment]
normal images: 

Simulator Screen Shot - iPad Pro (12 9-inch) (4th generation) - 2021-07-15 at 18 34 47



webp, converted as stickers, text is not allowed:

Simulator Screen Shot - iPad Pro (12 9-inch) (4th generation) - 2021-07-15 at 18 34 05

the screenshots are made on an simulator, the keyboard is configured to not be shown there. 
The half-transparent background is the default background of the SLComposeServiceViewController, the standard iOS comonent for sharing.

**Comment by r10s** [comment]
> webp, converted as stickers, text is not allowed:

offtopic - but why is that image in webp format? @dignifiedquire posted recently screenshots in the ios group that also arrive as stickers unexpectedly - so, maybe we should be a bit more conservative with the sticker-image-detection and use images when in doubt, esp. on sharing (keyboard is maybe differently)

**Comment by cyBerta** [comment]
> > webp, converted as stickers, text is not allowed:
> 
> offtopic - but why is that image in webp format? @dignifiedquire posted recently screenshots in the ios group that also arrive as stickers unexpectedly - so, maybe we should be a bit more conservative with the sticker-image-detection and use images when in doubt, esp. on sharing (keyboard is maybe differently)

I chose a webp image from https://en.wikipedia.org/wiki/WebP. We said that we would handle shared webp images as stickers. We can change that of course.

**Comment by cyBerta** [comment]
But I also wonder why @dignifiedquire's screenshot was in webp format.

**Comment by r10s** [comment]
> @r10s shall we just remove the option to share webp files as stickers? Maybe it causes more confusion than helping users to play with stickers.

yip, probably makes sense, seems as if webp is used eg. for screenshots, at least sometimes.

that does not affect sharing via keyboard, right?

**Comment by cyBerta** [comment]
I'm going to implement

> > @r10s shall we just remove the option to share webp files as stickers? Maybe it causes more confusion than helping users to play with stickers.
> 
> yip, probably makes sense, seems as if webp is used eg. for screenshots, at least sometimes.
> 
> that does not affect sharing via keyboard, right?

Yes it doesn't affect sharing via keyboard. I'm going remove that share-webp-as-stickers-part as  a separate PR.

**Review by r10s — APPROVED** [review]

**Pull request merged**
