### PR TITLE
ScrollView jumping improvements

### PR DESCRIPTION
**Pull request by Amzd**
In this PR I flipped the scrollView so now new messages automatically cause the rest of the messages to move up so we no longer need to programmatically scroll down when messages are sent and/or received.

### Fixes:
- #2232
- #2307 - since the scrollview in this PR starts with the newest message at the top (virtual top, actual bottom, because the tableView is flipped) this issue will never occur because even if the vc doesn't scroll anywhere, it will be showing your latest messages.
- Probably: #2305
- #2311
- When sending a long message, the chat doesn't scroll down to bottom of last message.
- #2233
- Maybe: #2161

### Intended changes:
- Less twitching when receiving/sending messages
- Smooth scrolling when searching
- No longer show inputAccessoryView when presenting other views (without having to resign firstResponder)

### Side effects:
**Messages are not refreshed until user stops editing** 
This is because we rely on selectedIndexPaths to keep which messages are selected, which can get out of sync with the actual message list when new messages are received or when they are automatically deleted. This was already the case before with deleted messages (eg through auto deletion) but is now also the case for new messages because messages are now pushed at the beginning of the indexPaths instead of at the end (because tableView is flipped).

This can be mitigated by tracking selected messages instead of relying on selectedIndexPaths.

**Messages don't float to the top when you have only few messages**
Since tableView now starts at the bottom, when you only have like 2 messages they are at the bottom instead of at the top.

This can totally be mitigated with a bit more effort.

**Empty state view is a bit higher up**
I think this is due to safeArea change to tableView but it is not a bad change because now it is still visible when keyboard is up (on iPhone SE anyway)

### Notes:

- I feel like it would be better if we did not use inputAccessoryViews that switch between keyboard and view controller attachment but instead just a normal view which we animate to always stay above the keyboard. This would eliminate the need for much of the first responder juggling we do right now and also eliminate the edge case where the input view is hidden when you don't expect it.

- Would be really nice to have tests that can confirm if the keyboard comes back after actions when expected.

### CODE REVIEW

**Comment by Amzd** [comment]
I think this PR already fixed #2312 by disallowing first responder when a the chatvc is presenting another vc, which is the conflict.

**Comment by r10s** [comment]
thanks a lot for diving into all that!

i already run the draft in its current state, and i have to say, that it improves things significantly already. wow!

**Comment by zeitschlag** [comment]
> This PR already fixed #2312 by disallowing first responder when a the chatvc is presenting another vc, which is the conflict.

lmk if you want me to revert it.

**Comment by Amzd** [comment]
> i am not sure what you mean here - i just tested receiving messages while using the input field - and that works as expected

I mean while selecting messages (long press message > more options)

> this is totally fine, and also how it was intended to work.

OK that's easy then. My reference (iMessage) keeps it at the top so I thought that was intended.

> please let us know, when it is ready-to-review - or if you have any questions

It is basically all I wanted to do for this PR, I opened it in draft because I wasn't sure if it was OK to create PRs of this size.

**Comment by Amzd** [comment]
The image from the read me showing the chat screen is no longer accurate since this PR (since messages float down instead of up here)

**Comment by Amzd** [comment]
[af65d6f](https://github.com/deltachat/deltachat-ios/pull/2315/commits/af65d6fabbfd12237491d9f2458586968386a296) broke first message scrolling while trying to prevent the empty state view from jumping up and down when scrollview appears.

**Comment by Amzd** [comment]
Resolved

**Comment by Amzd** [comment]
https://github.com/user-attachments/assets/0d8e585e-872a-4e5a-a416-c25d43050634

**Comment by Amzd** [comment]
@r10s I don't have permissions to add reviewers

**Comment by adbenitez** [comment]
I am **amazed** thanks a lot!!! :star_struck:

**Comment by Amzd** [comment]
> I am **amazed** thanks a lot!!! :star_struck: 

Wait then who am I?

**Pull request merged**
