### PR TITLE
Update deps

### PR DESCRIPTION
**Pull request by dignifiedquire**

### CODE REVIEW

**Comment by r10s** [comment]
very cool, all os will have the same defaults wrt move and watch now :)

**Comment by dignifiedquire** [comment]
@jonasreinsch also added a bugfix, sent messages weren't being shown properly. If you could push a new testflight once this is merged that would be great

**Comment by jonasreinsch** [comment]
@dignifiedquire thank you, will do!

https://github.com/deltachat/deltachat-ios/issues/38 should be unrelated to this bugfix (because incoming msgs are concerned), correct?

**Comment by jonasreinsch** [comment]
@dignifiedquire Testflight build should be out now.

**Pull request merged**
