### PR TITLE
[wip] Various improvements

### PR DESCRIPTION
**Pull request by dignifiedquire**
- feat: make libetpan a git submodule
- feat: make deltachat-core a git submodule
- feat: add `sentbox` and `mvbox` threads
- fix: load images sent from the right file location
- feat: update messagekit to 2.0

Depends on #29

### CODE REVIEW

**Comment by humanlikedisaster** [comment]
Maybe, can we merge it? Because I see various fixes and they can lead to merge conflicts in my current work.

**Comment by humanlikedisaster** [comment]
@dignifiedquire 
Can't build because 
/deltachat-ios/libraries/libetpan/build-mac/update.sh
is trying to get 
ftp://ftp.cyrusimap.org/cyrus-sasl/cyrus-sasl-2.1.26.tar.gz

and server is timed out.

can we change script to correct URL or just to push it to repo and not to check it from server side?

**Comment by dignifiedquire** [comment]
build issue: https://github.com/dinhviethoa/libetpan/issues/319

Applying this change in `build-mac/dependencies/prepare-cyrus-sasl.sh` to libetpan fixes it

```diff
 ARCHIVE_NAME=$ARCHIVE.tar.gz
 ARCHIVE_PATCH=$ARCHIVE.patch
 #url=ftp://ftp.andrew.cmu.edu/pub/cyrus-mail/$ARCHIVE_NAME
-url=ftp://ftp.cyrusimap.org/cyrus-sasl/$ARCHIVE_NAME
+#url=ftp://ftp.cyrusimap.org/cyrus-sasl/$ARCHIVE_NAME
+url=https://github.com/cyrusimap/cyrus-sasl/releases/download/$ARCHIVE/$ARCHIVE_NAME
 patchfile=cyrus-2.1.25-libetpan.patch
```

**Comment by dignifiedquire** [comment]
I am still working pretty heavily on this branch right now, and it is pretty messy, so not sure it is a good idea to merge yet

**Comment by humanlikedisaster** [comment]
@dignifiedquire 
Looked at the changes and they are really good!

Only question - what does "Camera" tab mean?

**Comment by hpk42** [comment]
As far as i know @dignifiedquire is happily using this branch for day-to-day activities.  Hope @jonasreinsch can skim/check the PR and merge soon, maybe with another testflight release then?

**Comment by dignifiedquire** [comment]
Just looked at the list of things from the readme, going to need the following fixes/improvements before I would mark them as done

- [ ] fix refresh when scrolled up (new bug I noticed)
- [ ] merge address book, when fetching things
- [ ] fix badge count, currently only a badge for either new notifications, or unread in the currently viewed chat
- [ ] display unread count in chat view
- [ ] view colored avatars in the chat view
- [ ] add timestamp to each messsage

Things I am currently working on/thinking about doing 

- [ ] QR Code
- [ ] Verifying users (scan user qr code and display their qr code)
- [ ] Video recording
- [ ] Audio recording
- [ ] Video messages inline
- [ ] Audio messages inline
- [ ] Gif messages inline
- [ ] Group details view, to manage groups
- [ ] Star messages (action + viewing them)
- [ ] Delete messages
- [ ] View Message Details
- [ ] Archive Chats
- [ ] View archived Chats

**Comment by r10s** [comment]
awesome :)

**Comment by jonasreinsch** [comment]
@dignifiedquire 

what do you say - should we just merge into master now? As far as I looked, everything seems good but at the same time I see that you are still working on the branch so not sure what's your preference there (I ask because above in the discussion you said you would prefer if we wait a bit with merging). Btw @hpk42 a build for TestFlight can also be made if the PR is not merged yet.

I would sometime in the future update build instructions in the README (because submodules are now used and because of the fix that has to be applied for libetpan).

Regarding the TestFlight build: I could prepare one with the old bundle ID, but perhaps its better to switch to the new bundle ID (com.delta.chat.ios) for that, too - @dignifiedquire you could try to prepare the build for TestFlight with the new bundle ID or alternatively add me to the team (I gather you already created an org dev account from the Delta Chat Apple Id, correct?). If the latter, I would need to be member both of the code signing team (in order to be able to prepare the build) and of the App Store Connect Team (in order to be able to upload TestFlight builds).

**Pull request merged**
