### PR TITLE
add help link and verison to settings

### LINKED ISSUE #278: show the version somewhere in the ui

### PR DESCRIPTION
**Pull request by r10s**
closes #278

### CODE REVIEW

**Comment by OzancanKaratas** [comment]
Hi @r10s, today I noticed, Delta Chat crashes when clicked Delete Account. Were there any issues reported? I cannot see.

**Comment by r10s** [comment]
hi @OzancanKaratas, i've just rewritten that part and tested it, at least it should work now.

we should really update the tesflight version these days :)

**Comment by OzancanKaratas** [comment]
I agree. ☺

**Comment by cyBerta** [comment]
I didn't notice that. If I remember correctly, I deleted my account some days ago during testing without any issues.

**Comment by cyBerta** [comment]
lgtm

**Pull request merged**
