### PR TITLE
Update korean translation

### PR DESCRIPTION
**Pull request by hellojaccc**
Updated korean translation. 

It is missing many strings compared to en.lproj, how can i fix that?

### CODE REVIEW

**Comment by r10s** [comment]
great that you want to take care of korean!

we do translations via transifex, https://www.transifex.com/delta-chat/public/ , you can log in there with your github handle.

once done, please tell us your transifex name so we can assign you as a translator for korean. alternatively, you can also request that on transifex and we will get a notification then, however, even then, it is saver to ping us here :)

**Comment by r10s** [comment]
nb: we are using one shared translations repo for ios/android/desktop - so, also android/desktop will benefit from the effort you will do for ios :)

**Comment by hellojaccc** [comment]
Hi, i requested to join team. @hellojaccc is my transifex nickname.

**Comment by r10s** [comment]
> Hi, i requested to join team. @hellojaccc is my transifex nickname.

@hellojaccc thanks a lot! i just approved your requests and also gave you the rights to change existing translations.

i think, we can close this pr then, i would be great if you can apply these few changes from this pr also on transifex. we pull all translations from transifex regulary, they will find their way to ios/android/desktop then.

**Comment by hellojaccc** [comment]
Thank you i appreciate it! I'll edit strings.

**Comment by r10s** [comment]
> Thank you i appreciate it! I'll edit strings. 

it is a good timing, btw, i think somewhen ~next week we do new releases, at least testflight. they will include korean updates then :)

**Pull request closed without merging**
