### PR TITLE
Fix memory leaks

### PR DESCRIPTION
**Pull request by cyBerta**
related to #772

### CODE REVIEW

**Comment by nayooti** [comment]
Crucial retain cycle was actionHandler of the messageInputBar. Not sure if the other weak-statements etc. were needed.

**Comment by cyBerta** [comment]
great catch! Thanks @nayooti for continuing this task. 
What is now still needed is work on DBDebugKit.

**Comment by nayooti** [comment]
@cyBerta What exactly make you think there are memory leaks in DBDebugToolkit?

**Comment by cyBerta** [comment]
> @cyBerta What exactly make you think there are memory leaks in DBDebugToolkit?

you need to reactive the out commented code in order to see them in the instruments tool.
Bildschirmfoto 2020-06-22 um 12 30 00

**Comment by cyBerta** [comment]
@nayooti DBDebugToolkit only leaks small amouts compared to the fixed leaks in this PR. I think we can merge that in and handle DBDebugToolkit in a separate PR. 
Can you please approve this PR?

**Pull request merged**
