### PR TITLE
Changed color of contact cell

### PR DESCRIPTION
**Pull request by nayooti**
fix for #509

### CODE REVIEW

**Comment by nayooti** [comment]
I will look into this.

**Comment by nayooti** [comment]
I looked at other competitor apps and at how Apple uses darkmode in their products. 

We're using the ContactCell for 

1.  displaying chats in the `ChatList`

2.for displaying contacts in some other lists. 

I would definitely stick to black for 1).
Look how Apple does this:
[Apple Guidelines](https://developer.apple.com/design/human-interface-guidelines/ios/visual-design/dark-mode/) 
I would make them gray for 2). 
How Telegram does it in their ChatDetail.

**Comment by r10s** [comment]
k, we can merge this, it is already an improvement.

whether to use "gray" or "back" on darkmode also depends a bit if we want to have some section headers or not, however, we can decide on that later, threre are lots of changes in this area anyway :)

**Pull request merged**
