### PR TITLE
Remove chat and chat list remove animation

### PR DESCRIPTION
**Pull request by humanlikedisaster**
Now you can remove chat (just swipe to left).
I've added Differ pod to make deletion/insertion animated (it's MIT).

### CODE REVIEW

**Comment by dignifiedquire** [comment]
As far as I can tell this does not actually delete something in the backend, this needs to call `dc_delete_chat`, and we probably also want archiving using `dc_archive_chat`. 

Also we probably want to use sth like https://github.com/SwipeCellKit/SwipeCellKit for the different actions on a chat.

**Comment by humanlikedisaster** [comment]
@dignifiedquire 
No, it's deletes chat. Look here
https://github.com/deltachat/deltachat-ios/pull/31/commits/b3520fa2d8dc293526d511c260db742b406fa127

Wrapper and ChatListController.

We can use it if it will have archive option in future. For current implementation there is no need for this.

**Comment by dignifiedquire** [comment]
you are right, I missed this sorry

**Comment by jonasreinsch** [comment]
@humanlikedisaster could you try to resolve the conflicts (sorry for the long time it did take me to merge https://github.com/deltachat/deltachat-ios/pull/30 )

**Comment by r10s** [comment]
I think this pr is a bit stale, closing this for now.

**Pull request closed without merging**
