### PR TITLE
Gallery: video thumbnails are generated in background thread

### LINKED ISSUE #792: Async thumbnail loading in the gallery
follow up for #748

### PR DESCRIPTION
**Pull request by nayooti**
closes #792

### CODE REVIEW

**Comment by cyBerta** [comment]
It doesn't fix the lagging completely. What works nicely is the Image cache, but on first loading scrolling is not smooth.
I think a reason could be that the loading jobs are not yet finished, but the cells are already about to be recycled. 
Invalidating of an image is not implemented in the current UIView extension.

**Comment by cyBerta** [comment]
It becomes very obvious if you have many videos right after each other in the gallery.

**Comment by nayooti** [comment]
Interesting catch. But definitely makes sense. I‘ll look into this.

**Comment by nayooti** [comment]
So, I tested it and on my device (Iphone SE) the scrolling is very smooth. You can see the thumbnails appear with delay but it does not affect scrolling at all. Also opening the gallery is instant.

**Comment by nayooti** [comment]
I was actually currently working on this PR.

**Pull request merged**
