### PR TITLE
improve accessibility of voice message recording #493

### LINKED ISSUE #493: VoiceOver silences when voice message button is pressed
In a chat window, VoiceOver silences after voice message button is pressed. I don't know why, but it does not happens in the WhatsApp and Skype.

### PR DESCRIPTION
**Pull request by cyBerta**
fixes #493

### CODE REVIEW

**Comment by cyBerta** [comment]
> if this is possible, maybe we can move the "double tap again to send recorded message" to the attach-menu?

Can you please explain that a little bit more? Do you mean sth. like hold-to-record - as it is done in Android?

**Comment by cyBerta** [comment]
> i just played around with whatsapp: they just do not stop voice-over on recording, wondering, if that wouldn't be a better fix for us.

I can try to figure out that

**Comment by cyBerta** [comment]
> however, there is no way to cancel the sending, or?
> (the cancel button is there, but you cannot navigate to it by voice-over)

that's correct. It's more like hold-to-record -> if you started once you cannot cancel sending it anymore.

**Comment by r10s** [comment]
i'll do an alternative pr that describes what i mean.

**Comment by cyBerta** [comment]
closing in favor of #690

**Pull request closed without merging**
