### PR TITLE
Update deps for ios14

### PR DESCRIPTION
**Pull request by cyBerta**
- fixes not appearing images on iOS14
- current pod versions generate additional xconfig files for all pods. I added them since they need to be removed with every update otherwise

### CODE REVIEW

**Comment by r10s** [comment]
lgtm - however, better merge this to master and rebase messageKitReplacement on top of that.

- images are probably broken on ios14 also without messageKitReplacement
- this keeps the changes in messageKitReplacement low and maintainable

**Comment by cyBerta** [comment]
ok, makes sense

**Comment by r10s** [comment]
great!

**Comment by r10s** [comment]
if in doubt, open a new pr, not sure if once can change the merge-target

**Pull request closed without merging**
