### PR TITLE
Unblock blocked contacts

### PR DESCRIPTION
**Pull request by cyBerta**
targets #211 
- includes the same alert as in android
- search is disabled

Screen Shot 2019-09-18 at 18 59 35

### CODE REVIEW

**Comment by cyBerta** [comment]
I could add the name of the selected contact to the alert title...

**Comment by r10s** [comment]
looks great! a search is not really needed, at least not for now, this is fine. i will check this out.
the "< back" button looks android-ish, should be "< settings" or so.

**Comment by r10s** [comment]
> I could add the name of the selected contact to the alert title...

yeah, this makes sense here as doable without changing the already translated strings.

**Comment by r10s** [comment]
some nitpicking: the checkmarks are not needed in the list of blocked contacts.

**Comment by cyBerta** [comment]
I'll adjust that tomorrow.

**Comment by r10s** [comment]
great, now i can contact all the ppl again i blocked for testing reasons the last days :)

**Pull request merged**
