### PR TITLE
PreviewController - remove list item when accessed from Gallery

### LINKED ISSUE #785: Gallery follow-up: remove list button in gallery detail
Go to Chat -> Chat Detail -> Gallery -> tap any image -> the Gallery Detail (`PreviewController.swift`) view is now showing:

In the bottom right there is an icon showing:
IMG_7F8B30D09FE1-1

The icon is no longer needed and should be removed.

### PR DESCRIPTION
**Pull request by nayooti**
closes #785 

### Observation: 
- On Iphones the the list button appears in a **bottom toolbar**
- On Ipads the list button appears in the **navigation bar** in the top
- All toolbar items are only accessible via subview traversing and can only be modified to a certain degree
- Toolbar at `viewDidLoad` always nil -> so customisation has to be done on `viewWillAppear`

Unfortunately the QL-toolbars are very resistant to customisation.  The solution was:
- traverse search the NavigationBar / BottomToolbar
- in the toolbar find the list item (can be identified by accessibility identifier)
- now: isHidden, remove etc. don't work, so the only solution was to disable it (or remove action), and hide it by setting `tintColor =.clear`

In case PreviewController is inside a navigationController this approach isn't meant to work, so the customisation won't be visible if the PreviewController is accessed from ChatView. 

[Update:]
for iOS 13.4 and lower the bottomToolbar is not customisable, so we cover it by a fake toolbar.

### CODE REVIEW

**Comment by cyBerta** [comment]
unfortuantely this doesn't work reliable on my iPhone SE. In rare cases the list icon disappears but most of the time it's still visible. It seems to be a timing issue or maybe the changes get overwritten again?

**Comment by nayooti** [comment]
> unfortuantely this doesn't work reliable on my iPhone SE. In rare cases the list icon at the bottom disappears but most of the time it's still visible. It seems to be a timing issue or maybe the changes get overwritten again?

Are you accessing via ChatDetail or directly via ChatView?

**Comment by nayooti** [comment]
> unfortuantely this doesn't work reliable on my iPhone SE. In rare cases the list icon at the bottom disappears but most of the time it's still visible. It seems to be a timing issue or maybe the changes get overwritten again?

it works on my Iphone Pro (100%), but on my SE it doesn't neither.

**Comment by nayooti** [comment]
For iOS 13.4 and lower I added a fake-toolbar, that covers the real toolbar and imitates it's behaviour. Quite hacky and I am not 100% happy with this.
But I tested for Ipad, Iphone 13.4, 12.4 and Iphone 13.5 and the list button is gone now, so I think it's good for now.

For future iOS releases we should have an eye on this, but the worst thing that can happen, that the list button will be visible again.

**Comment by cyBerta** [comment]
Hm... this adds quite a lot of code to hide one single button. I think the complexitiy is over the top for what we want to archieve and that it is reasonable to support only 13.5 and newer.
@r10s can you have a look at it, too?

**Comment by nayooti** [comment]
Ok, I give up.

I went back to the state were the list item should have hidden for iOS13 devices and unfortunately the list button is suddenly back. It disappears when start pulling down the image. 

So at this point I would suggest to live with the list button. So I close this for now.

**Pull request closed without merging**
