### PR TITLE
tweak contact lists

### LINKED ISSUE #391: add "me" to create-chat contact-selection
probably a flag only ...

### PR DESCRIPTION
**Pull request by r10s**
closes #391

### CODE REVIEW

**Comment by cyBerta** [comment]
the language/strings updates are on purpose here?

**Comment by r10s** [comment]
> the language/strings updates are on purpose here?

no, they are already on master by -
https://github.com/deltachat/deltachat-ios/commit/6a89cb1ec7b5a1405ff53e3f306ed1793b1ff494 - not sure where they come from, maybe a rebase is needed. i will have a look.

**Comment by r10s** [comment]
@cyBerta a rebase did the trick, now it should be better :)

**Comment by cyBerta** [comment]
lgtm

**Pull request merged**
