### PR TITLE
Message kit replacement

### PR DESCRIPTION
**Pull request by cyBerta**
todo to make the chat-view usable again:
- [x] open the chat at the end of the list (scroll down) (@cyBerta)
- [x] add keyboard/input-field, attach-button, send-button (@cyBerta)
    - [x] maintain scroll position if keyboard expands (@cyBerta )
    - [x] hide keyboard when scrolling down (is there a flag or so for that? other apps seem to hide the keyboard only when scrolling down near the bottom) (currently, it is not possible to hide the keyboard at all) (@cyBerta )
    - [x] scroll down on send (@cyBerta )
- [x] fix empty state view (message is not wrapped, see message after creating a new group) (@cyBerta )
- [x] add image avatars  (@cyBerta)
    - [x] tap on image avatar should open user-profile 👈 (@cyberta)
- [x] add text-view
  - [x] make links clickable 👈 (@cyBerta )
- [x] add image-view, including gif  (@cyBerta)
   - [x] a tap on image-view should go to gallery as before 👈 (@cyBerta )
   - [x]  fix cell size calculation of gif / gif + text messages [*]
- [x] add video-view, incl. play-button 👈 and opening in gallery 👈 as before (@cyBerta )
- [x] add audio-view (@cyBerta )
- [x] add file and other views (@cyBerta)
    - [x] a tap on file-view should open documents as before 👈 (@cyBerta )
- [x] add delivery-line (date/time, checkboxes), should go inside the bubble this time to allow backgrounds in a subsequent pr (@cyBerta )
- [x] add generic context menu (copy/info/delete/forward) 👈 (@r10s)
- [x] add a delegate-or-so to get different events from BaseMessageCell (roughly marked as 👈 above), i would avoid creating different delegate-classes for all types, a single delegate-class added to BaseMessageCell should do the job, it can contain all events for the subclasses then. (@r10s)
- [x] call dc_markseen_msgs() for messages scrolled into view. this also makes "disappearing messages" work again. (@cyBerta)
- [x] autocrypt-setup message handling in saved messages (@cyberta)

things to fix:
- [x] scrolling blocks from time to time (@r10s, might be fixed by #940)
- [x] use adaptive font sizes as before, see https://github.com/deltachat/deltachat-ios/pull/810 (@cyBerta )
- [x] on empty chats, messages get out-of-view when posted as they stuck at the upper border of the screen - and that is shifted out-of-view by the virtual keyboard. see eg. new saved-messages chat, posting a message there will make it invisible first. (@cyBerta )
- [x] scrolling is still flaky, when opening a chat with recent images, things are not really scrolled down. maybe this is related to groups only, or maybe to [*] i could not reproduce that for "saved messages" EDIT: this seems to be vastly improved by #921, however, i found another, fortunately now reproducible issue:
- [x] if the last (?) messages contains media+text, the initial scrolling position is wrong. can be reproduced eg. by sharing an image plus some text to "Saved messages"
- [x] images not shown on ios14 (@cyBerta )
- [x] if the input field disappears and reappears the scroll position is not correct (offset of input field height is not reapplied)
- [x] the scroll position should be retained if the user opens chat message details and goes back to the chat (@cyBerta )
- [x] adapt padding for messages including images
- [x] hide name + avatar for 1:1 chats

optional/later:
- if possible: avoid frequent appearing/disappearing of the input field, see #427
- switching from dark- to lite-mode lacks redraw of some cells
- tweak padding and sizes
- removing MessageKit
- scroll to correct position on search
- background image

### CODE REVIEW

**Comment by r10s** [comment]
@cyBerta can you drop a few lines about reasoning to the source code here and there? eg. why the ChatTableView is needed and why/when this becomes a firstResponder. no big explanations, just one line or so top of class declaration.

**Comment by cyBerta** [comment]
@r10s I think we're more or less done with this ticket.

**Comment by r10s** [comment]
> @r10s I think we're more or less done with this ticket.

yeah, looks pretty good. thanks for getting that through :)

i just rebased it and will test it out another day on my phone before finally merging :)

**Review by r10s — APPROVED** [review]

**Comment by r10s** [comment]
looks good so far, i'll merge that in now; there are some minor issues but they can be targeted in separated tickets - esp. as also the MessageKit had several issues :)

great job, @cyBerta :)

**Comment by mlyongardiner** [comment]
@r10s and @cyBerta -
I'm not amazing with Git/Github, how can I use this implementation? MessageKit is an amazing project but it doesn't load messages as efficiently as I need in my project. Any help would be great!

**Pull request merged**
