### PR TITLE
tweak qr-code view and tabbar

### LINKED ISSUE #334: update icons in the tabbar
- qr-code-tab should show a qr-code
- chat-icon could be nicer

### LINKED ISSUE #436: quick-fix qr code view
- remove the upper field with selfavatar, name etc.
- make qr code larger

### PR DESCRIPTION
**Pull request by cyBerta**
*  in QR Code ViewController
* in TabBar

closes #334 
closes #436

### CODE REVIEW

**Comment by cyBerta** [comment]
tabbar

**Comment by cyBerta** [comment]
I'm adding the accessibilty labels to the chat view, therefore WIP again

**Comment by r10s** [comment]
looks great!

some nitpicking to the icons: can we do the delta-logo a _little_ bit smaller? so that it has the same heitght as the settings-button? (the resolution of the image as such should not change, however, just a bit smaller, centered, this would result in a slightly wider transparent border)

and: can you upload the adapted svg to the interface repo as delta-ios-chatlist.svg or so?

**Comment by OzancanKaratas** [comment]
I think merge this branch into paper-clip. I feel that this will conflict with paper-clip.

**Pull request merged**
