### PR TITLE
Dark mode

### LINKED ISSUE #163: ios dark mode support is very poor
Some parts are inverted, some are not. Some have very poor contrast, or strange artifacts.

### PR DESCRIPTION
**Pull request by cyBerta**
closes #163

### CODE REVIEW

**Comment by r10s** [comment]
looks great!

one thing i noticed: the pr changes the font-size of the centered chat-system-messages as "member xy added" or "setup changed for xyz". seems as if this is the same size as the in/out bubbles now - but is should be a bit smaller as before.

**Comment by cyBerta** [comment]
oh, ok. Thanks for pointing it out

**Comment by r10s** [comment]
another thing: also the hyperlinks are always black (when it crosses your way: also some works as yesterday, gestern etc. are turned into links. we should stop that, it is not reliable and not really helpful) (if it not crosses your way, we'll do an issue :)

**Comment by cyBerta** [comment]
> another thing: also the hyperlinks are always black (when it crosses your way: also some works as yesterday, gestern etc. are turned into links. we should stop that, it is not reliable and not really helpful) (if it not crosses your way, we'll do an issue :)
there's already an issue: https://github.com/deltachat/deltachat-ios/issues/347
I'll do it there

**Comment by cyBerta** [comment]
besides that, it's ready for review round 2

**Pull request merged**
