### PR TITLE
WIP: First steps to show open or closed padlocks.

### LINKED ISSUE #400: Chat does not show lock even if message was encrypted
- Device: iPhone SE
- iOS version: 13.2.3
- Delta Chat version: 0.950.0 (from testflight)
- Expected behavior: Show a lock for each message if it was encrypted.
- Actual behavior: No lock is shown.
- Steps to reproduce the problem: Send or receive a message with a mutually encrypting contact
- Screenshots:

deltachat-ios-missing-lock-1

deltachat-ios-missing-lock-2

### PR DESCRIPTION
**Pull request by pabzm**
Closes #400

Shuffled the code around a little to make it work for sent and received
messages as well. Didn't test it, though, as I don't have MacOS available.

I'd love to hear some feedback already. Is this going into a pursuable direction?

Please note that I am very new to Swift. Don't hesitate to tell me what should be improved, I'll interested in learning!

### CODE REVIEW

**Comment by cyBerta** [comment]
Hey Pabz, nice that you're willing to hack on iOS 👍 !
I think it makes sense to work on a Mac or VM if you're patient in case you want to contribute to iOS. These changes doesn't show a lock, but I didn't wrap my head around it why not - mainly because the overall reviewing process seems to be very difficult under these conditions. Are there any chances that you're getting a setup to test your code before you file PRs?

**Comment by pabzm** [comment]
Thanks for the check and hints!
I wasn't assuming that this first shot would work as expected instantly, but only to help getting started with this issue.

But I'll have a look and try to get a working setup. Feel free to close this if you don't want it to linger around until it works.

**Comment by cyBerta** [comment]
I'll close this PR for now. @pabzm anyway, I'm happy to help with hacking on iOS in case you get a dev environment!

**Comment by pabzm** [comment]
I tried to build a dev environment in a VM but I failed. So I will withdraw from my attempt.

Should I delete the branch?

**Comment by r10s** [comment]
please just leave the information, it may help on the next attempt :)

**Pull request closed without merging**
