### PR TITLE
update to new tx tool

### PR DESCRIPTION
**Pull request by r10s**
closes https://github.com/deltachat/deltachat-ios/issues/1763

### CODE REVIEW

**Comment by r10s** [comment]
for review: no need to understand that fully :) it is more about getting aware that things were changed in this area :) (changes are needed as the "old" transifex tool is sunset and there are slight differences with the new one)

**Comment by cyBerta** [comment]
For me this PR is still creating a lot of error messages, similar to this one:

```
Traceback (most recent call last):
  File "/usr/local/bin/tx", line 5, in <module>
    from txclib.cmdline import main
ModuleNotFoundError: No module named 'txclib'
node:internal/fs/utils:347
    throw err;
    ^

Error: ENOENT: no such file or directory, open 'tmpAndroidTranslations/de/strings.xml'
    at Object.openSync (node:fs:591:3)
    at Object.readFileSync (node:fs:459:35)
    at parseXMLAndAppend (/Users/cyberta/workspace/deltachat-ios/scripts/convertTranslations.js:237:17)
    at convertAndroidToIOS (/Users/cyberta/workspace/deltachat-ios/scripts/convertTranslations.js:251:19)
    at Object.<anonymous> (/Users/cyberta/workspace/deltachat-ios/scripts/convertTranslations.js:293:1)
    at Module._compile (node:internal/modules/cjs/loader:1205:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1259:10)
    at Module.load (node:internal/modules/cjs/loader:1068:32)
    at Module._load (node:internal/modules/cjs/loader:909:12)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:82:12) {
  errno: -2,
  syscall: 'open',
  code: 'ENOENT',
  path: 'tmpAndroidTranslations/de/strings.xml'
}

```

Do I have to do anything else than to call [scripts/tx-pull-translations.sh](https://github.com/deltachat/deltachat-ios/pull/1764/files#diff-400f9f1b60f33b613e83e278ad542b4efdf8534fc0a6df1d4a8cf932fbd6e931)?

**Comment by r10s** [comment]
did you insalled and set up the new `tx` utility (written in Go instead of Python)?

**Comment by cyBerta** [comment]
I've reinstalled  tx according to https://developers.transifex.com/docs/cli 

```
curl -o- https://raw.githubusercontent.com/transifex/cli/master/install.sh | bash
```

still the same

**Review by cyBerta — APPROVED** [review]
works perfectly!

only tx migrate was missing for me. Since there are only few people working on the repository it's maybbe not worth to write a little documentation. For the record dear reader, please follow these instructions until the end.

**Comment by r10s** [comment]
this pr contains the result of `tx migrate`, so, in theory, it should work also for new ppl. no idea, why it did not work for you, maybe it does some magic if old tx was installed :)

**Pull request merged**
