### PR TITLE
Document picker

### LINKED ISSUE #376: add option to attach files
the option should pop up in the paper-click-menu, together with "Camera", "Gallery" etc.

i think there is a system view where the user can select the things to send, the selection just goes to [dc_msg_set_file()](https://c.delta.chat/classdc__msg__t.html#ae3d4b2a4ed4b10dbe13396ff7739160e) then.

EDIT: corresponding forum thread: https://support.delta.chat/t/beta-dc-ios-attaching-files/667

### PR DESCRIPTION
**Pull request by cyBerta**
closes #376

@r10s, @nayooti  it's quite basic for now. Can you have a look at it please?

### CODE REVIEW

**Comment by nayooti** [comment]
Looks good.

**Comment by cyBerta** [comment]
@r10s, @nayooti:  Ok, I've added the iCloud drive access

**Comment by cyBerta** [comment]
merging it as @nayooti has approved the PR

**Comment by r10s** [comment]
good stuff :)

**Pull request merged**
