### PR TITLE
 add counter to search-headers

### LINKED ISSUE #579: add counter to search-headers
the search-headers currently read only "CHATS", "CONTACTS", "MESSAGES".

it would be great, if we can add the number of results to each header, so "5 CHATS", "6 CONTACTS", "7 MESSAGES".

the strings needed for that are already available and translated as `n_chats`, `n_contacts` and `n_messages` (the strings have different singular/plural forms, grep for n_members to get an idea how to use it)

btw, this is what it looks like on android:

### PR DESCRIPTION
**Pull request by nayooti**
fixes #579

### CODE REVIEW

**Comment by r10s** [comment]
why did you close this?

in general, it is helpful to add some words when closing a pr, referencing the subsequent, some reasons etc. esp. if the pr is not WIP, was tested and approved etc. :)

**Comment by nayooti** [comment]
In other projects PR are/can/should always be merged/closed by the guy who
implemented it, after it has been approved by the reviewer.
Sorry if that wasn’t appropriate.

bjoern <notifications@github.com> schrieb am Sa. 21. März 2020 um 19:47:

**Comment by r10s** [comment]
sure - i would not have asked if the pr was merged by you :) - but it was closed and without merging, therefore i ask. maybe you wanted to merge and hit "close" accidentally?

**Comment by nayooti** [comment]
Ok, this was by accident then.

bjoern <notifications@github.com> schrieb am Sa. 21. März 2020 um 20:34:

**Comment by r10s** [comment]
k, so i merge that ✊

and sure, our policy is the same as you expected above - if a pr is approved by someone the author may merge it.

**Pull request merged**
