### PR TITLE
show padlock if message was encrypted (#400)

### LINKED ISSUE #400: Chat does not show lock even if message was encrypted
- Device: iPhone SE
- iOS version: 13.2.3
- Delta Chat version: 0.950.0 (from testflight)
- Expected behavior: Show a lock for each message if it was encrypted.
- Actual behavior: No lock is shown.
- Steps to reproduce the problem: Send or receive a message with a mutually encrypting contact
- Screenshots:

deltachat-ios-missing-lock-1

deltachat-ios-missing-lock-2

### PR DESCRIPTION
**Pull request by cyBerta**
closes #400 
takes light and dark mode into account

### CODE REVIEW

**Comment by r10s** [comment]
great! i'd like to have the padlock in the date-gray, also directly right of the date. i will do a commit on top of this pr.

**Comment by cyBerta** [comment]
> great! i'd like to have the padlock in the date-gray, also directly right of the date. i will do a commit on top of this pr.

I think the easiest way would be to prepare the png files for the light mode accordingly

**Comment by r10s** [comment]
yeah, sth. like that :) i will have a look.

**Comment by cyBerta** [comment]
Screen Shot 2020-03-05 at 16 10 16
Screen Shot 2020-03-05 at 16 10 52

**Pull request merged**
