### PR TITLE
Lint fixes

### LINKED ISSUE #1540: empty enum argument violation
i have no idea what these warnings wants to say to me:

WelcomeViewController.swift:

AppDelegate.swift:

these are just two examples, there are more corresponding warnings.

imu, the functions have just no arguments. is this a false positive of the linter?

### PR DESCRIPTION
**Pull request by cyBerta**
closes #1540 and some other lint (and real) issues.

### CODE REVIEW

**Review by r10s — COMMENTED** [review]
adding 31mb binary data to the repo looks like an accident to me ...?

**Comment by cyBerta** [comment]
> adding 31mb binary data to the repo looks like an accident to me ...?
> 
> not sure, however, already now, there are 40mb in the Pods directory, maybe this is just the way ...

This extra MBs is only fetched locally,  but not pushed to the repository, or?! I think that's the way it is.

**Comment by r10s** [comment]
> This extra MBs is only fetched locally, but not pushed to the repository, or?! 

it is in this pr:

Screen Shot 2022-04-22 at 12 52 50

however, yes, if that is the way to go, then that's not great but okay.

**Comment by cyBerta** [comment]
> however, yes, if that is the way to go, then that's not great but okay.

that's the way to go, unforunately.

**Review by r10s — APPROVED** [review]

**Pull request merged**
