### PR TITLE
Connectivity view

### LINKED ISSUE #1299: add connectivity view
- [x] in the chatlist's title bar, show the current state as returned from the new api [`dc_get_connectivity()`](https://c.delta.chat/classdc__context__t.html#a80bf9812eb5a50f8eb097cbe72df1096).  
for the state DC_CONNECTIVITY_CONNECTED we show the string "Delta Chat" as before, for the other states, show the strings `connectivity_getting_new_msgs`, `connectivity_connecting` and `connectivity_not_connected` 
we do not want to show dots or other icons currently.
the text should be updated on [`DC_EVENT_CONNECTIVITY_CHANGED`](https://c.delta.chat/group__DC__EVENT.html#ga3ced1bbde752feba46ab089611287d71).
(corresponding [android code](https://github.com/deltachat/deltachat-android/blob/b3fea81bed308275425e0136233465f589cf4fe0/src/org/thoughtcrime/securesms/connect/DcHelper.java#L79))

- [x] a tap on the chatlist's title bar text (so also on "Delta Chat") should open `ConnectivityViewConroller` (based on `WebViewViewController`) that just shows the html-code returned by [`dc_get_connectivity()`](https://c.delta.chat/classdc__context__t.html#a98d41f00d9a96d83a662f39d0fc23afb).  
the page should be updated on [`DC_EVENT_CONNECTIVITY_CHANGED`](https://c.delta.chat/group__DC__EVENT.html#ga3ced1bbde752feba46ab089611287d71).

- [x] the same `ConnectivityViewConroller` should be accessibe from the settings (entry above "help") (maybe with disclosureIndicator and textLabel from `dc_get_connectivity()`, if so, it should also be updated on `DC_EVENT_CONNECTIVITY_CHANGED`)

all that is implemented on android at https://github.com/deltachat/deltachat-android/pull/1860 (cc @Hocuri - did i missed an important point?)

### PR DESCRIPTION
**Pull request by cyBerta**
closes #1299

### CODE REVIEW

**Comment by r10s** [comment]
did a quick functional test:
- the app crashes when switching flightmode on/off - unfortunately, also the connection to a debugger is lost, so i could not easily check a log; i also failed in reproducing, but we should double-check
- the font-size in the title bar is increased, it is now too large (cmp. system "Settings" title with dc ones) - that does not only affect the chatlist but all views

**Comment by cyBerta** [comment]
Thanks for having a look at the PR.

> the update of the title bar is not always happening, could not really debug that because of the crashes :) (seems as if the first update works, i have never seen subsequent update when switching flightmode several times on+off)

I think this issue is core related. I've seen the same problem and added a little bit more verbose logging with commit https://github.com/deltachat/deltachat-ios/pull/1300/commits/063402e5e1fe0e093234a5b3d83fc154d5c56ddd. 
When turning on flightmode we're getting immediately `DC_EVENT_CONNECTIVITY_CHANGED`. If I call dc_get_connectivity() directly afterwards the state is still 4000 (`DC_CONNECTIVITY_CONNECTED`).

**Comment by r10s** [comment]
> I think this issue is core related.

hm, on android we do not have that issue - or are events somehow debounced there? cc @Hocuri

**Comment by cyBerta** [comment]
https://github.com/deltachat/deltachat-android/pull/1860/files doesn't seem to have debouncing implemented. 
I'm wondering how if multi-account is playing a role here. We're getting the event for each account but we also process the event on each dcContext (`let dcContext = dcAccounts.get(id: event.accountId)`. On any of those dcContext the result of  `dc_get_connectivity` is correct

**Comment by Hocuri** [comment]
> hm, on android we do not have that issue - or are events somehow debounced there? cc @Hocuri

No. But I suspect that the Android system somehow debounces the updating of the title bar.

Generally we can debounce connectivity events in the core, maybe Desktop will also need that, anyway

**Comment by cyBerta** [comment]
I don't think this issue is related to debouncing. To me, it looks like the detection of the current connectivity doesn't work reliable on iOS.
We're having a swift pod called 'ReachabilitySwift' that does a similar job. We _could_ use that platform specific implementation instead of the core as a workaround.

**Comment by cyBerta** [comment]
@r10s I couldn't reproduce the crash yet. Would it be possible to get the logs and attach them here?

**Comment by r10s** [comment]
>  Would it be possible to get the logs and attach them here?

i'll have a look, however, debugger is detached by the crash, so, not sure what there is available locally.

**Comment by cyBerta** [comment]
I've created a ticket here: https://github.com/deltachat/deltachat-core-rust/issues/2547

**Review by r10s — APPROVED** [review]
lgtm, the last commit however requires https://github.com/deltachat/deltachat-core-rust/pull/2550 to be merged.

@cyBerta i think, you should also check my latest commits :)

**Comment by r10s** [comment]
> lgtm, the last commit however requires deltachat/deltachat-core-rust#2550 to be merged.

that is merged now and i rebased the pr.

**Comment by r10s** [comment]
\o/

**Pull request merged**
