### PR TITLE
refresh title bar when webxdc app is open and app changed

### LINKED ISSUE #1924: webxdc title bar not updated in document title changes
if the app is opened and the document title changes, the title bar is not updated, see https://github.com/deltachat/deltachat-android/pull/2664

### PR DESCRIPTION
**Pull request by adbenitez**
this can happen if the document title changed so refresh title

close #1924

### CODE REVIEW

**Comment by adbenitez** [comment]
some blind programming here, I couldn't even check if it compiles at all, feel free to take over this PR and improve :+1:

**Comment by r10s** [comment]
thanks ❤️ i'll check that ✊

**Review by r10s — APPROVED** [review]
impressive! 😎 just for interest: did you even look onto the screen? anyways, it does not only build - but it also works!

**Comment by adbenitez** [comment]
I did look to the screen but not me nor my editor could recognize, syntax-highlight or properly indent such weird language :dizzy_face:

**Pull request merged**
